### ISSUE TITLE
Recherche : bridge (Stable Coin)

### ISSUE THREAD

**Issue by RuddyCHAM** [AlyraButerin/allfeat-funding#12]
En tant que: Equipe

Nous voulons: Etudier les façons de mettre en place un bridge pour avoir un stable coin 

Afin de: mieux quantifier et assurer la valeur éstimée et obtenue par les fans

Conditions: Compilation des solutions existantes transposables à notre projet

**Comment by ArnaudSene** [comment]
Schema pushed to "Schema repo" in draft mode.

**Comment by ArnaudSene** [comment]
Solution de bridge centralisé choisie.
Version 1 en mode MVP
