### ISSUE TITLE
Dead line choix de la fonctionalité 1

### ISSUE THREAD

**Issue by RuddyCHAM** [AlyraButerin/allfeat-funding#8]
Date limite pour choisir la première fonctionnalité à développer 

le 08/05/2024,

En tant que: Equipe

Nous voulons: Nous arrêter sur une idée précise qui sera la première étape de notre projet globale

Afin de: Commencer à développer une application fonctionnel 

Conditions: réalisation d'un document définissant les spécifications   (cahier des   charge)

@ArnaudSene @YoannRDC @RuddyCHAM @ibourn

**Comment by ibourn** [comment]
issue transférée sur le bon repo

**Comment by ArnaudSene** [comment]
La fonctionnalité choisie est la plateforme de financement participatif avec 3 choix, 

1. don hors campagne de financement
2. don avec campagne de financement sans DAO
3. don avec campagne de financement avec DAO

L'application de bridge étant un préalable
